# Aleksandar Obradovic
- orcid: 0000-0002-8009-0186

- id: doi:10.1016/j.eururo.2022.09.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0302283822026331-gr4.jpg
  date: 2022-9-13
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1158/1078-0432.CCR-21-3570
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/28/10/1/m_clincanres_28_10_cover.png?Expires=1670637786&Signature=jSMXWL0ltcrOtSRQQAGCRH-htWusGEmusO9J58m3BPV24G3gIwSprQyEwn6HQGwYikYFLIWmSuYWKe17oFkbGNgJxoEPmcH0Fxv0nes5mSGeJVnJBXy8nj5wDug4urIglbhX9dkP5cgLgDJXCz9ZaoC8iaeg8NNcT0QQvYo0mT7udcAY8F5dODrZSVE1UA5QU8u01P2hHdqKj46yjAYdrs8W3QSCfH15ecjTaFmAsCGIzXP~nW8l2Lxi9sYzZ1wqtWZPnZOczrcSSX4WAz9UBjOSaWgYR2pkyW8l7EdaHwjEl3lHas-noLD6t0Hyww7ezb-2aMsHb9n7izJ6kiHqng__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2022-5-15
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology
