# Aleksandar Obradovic
- id: doi:10.1016/j.eururo.2022.09.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0302283822026331-gr4.jpg
  date: 2022-9-13
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1158/1078-0432.CCR-21-3570
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/28/10/1/m_clincanres_28_10_cover.png?Expires=1670637786&Signature=jSMXWL0ltcrOtSRQQAGCRH-htWusGEmusO9J58m3BPV24G3gIwSprQyEwn6HQGwYikYFLIWmSuYWKe17oFkbGNgJxoEPmcH0Fxv0nes5mSGeJVnJBXy8nj5wDug4urIglbhX9dkP5cgLgDJXCz9ZaoC8iaeg8NNcT0QQvYo0mT7udcAY8F5dODrZSVE1UA5QU8u01P2hHdqKj46yjAYdrs8W3QSCfH15ecjTaFmAsCGIzXP~nW8l2Lxi9sYzZ1wqtWZPnZOczrcSSX4WAz9UBjOSaWgYR2pkyW8l7EdaHwjEl3lHas-noLD6t0Hyww7ezb-2aMsHb9n7izJ6kiHqng__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2022-5-15
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1002/path.5830
  image: https://onlinelibrary.wiley.com/cms/asset/35734156-4f8a-43f6-8224-38e1ca03aa77/path5830-fig-0001-m.jpg
  date: 2021-11-3
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology
   
#2016-10-21
- id: doi:10.1126/sciimmunol.aah3732
  image: https://www.science.org/cdn-cgi/image/width=400/cms/asset/8086faf2-5472-4b1b-b40f-6fc96af7afba/sciimmunol.2022.7.issue-77.largecover.jpg
  date: 2016-10-1
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1111/ajt.14251
  image: https://onlinelibrary.wiley.com/cms/asset/5f154fda-7bbc-4df0-8935-adf27c5f2f9a/ajt.2017.17.issue-8.cover.jpg
  date: 2017-3-1
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology
    
- id: doi:10.1172/jci.insight.121256
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6129121/bin/jciinsight-3-121256-g161.jpg
  date: 2018-8-9
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

#2018-11-15
- id: doi:10.1172/jci.insight.124086
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6302945/bin/jciinsight-3-124086-g085.jpg
  date: 2018-11-1
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1016/j.stem.2018.11.007
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1934590918305435-fx1.jpg
  date: 2019-2-7
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1172/JCI124358
  image: https://dm5migu4zj3pb.cloudfront.net/manuscripts/124000/124358/medium/JCI124358.f1.jpg
  date: 2019-3-28
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

#2019-10-25
- id: doi:10.1186/s40425-019-0758-y
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs40425-019-0758-y/MediaObjects/40425_2019_758_Fig1_HTML.png?as=webp
  date: 2019-10-1
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1111/ajt.15533
  image: https://onlinelibrary.wiley.com/cms/asset/bcf8def5-571f-4bb6-8500-a48289dac414/ajt.v20.1.cover.jpg
  date: 2019-7-18
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology

- id: doi:10.1158/1078-0432.CCR-19-3372
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/26/13/5/m_clincanres_26_13_cover.png?Expires=1670672831&Signature=oA7~tg4Mu8yG87gonUWuDY7O8O6w-vpd-ZD3zfandGMPzJ2oLPQaThtcfa32BwoWT0eJ-QUiA0mrWAnW6dxpu3qBttoFCfrX-f8JKHnOMJHwe4UqbU2REtCWX7kqn3VEA86ci-R6Fxk2ZU6Mp3F6eej60daLnQ~7zKmlYCvNdavKDu6U~L0V236~XQA13LL6zasdQ~pi9GHqTpq3AIL4s8lrIZdhbocUXtupFW79IZ-p-4jd5SclOi4t-ffEa-IxvIy95~IPmqzn1OAPmQAgGZaN0-BlQHcSuAZGNT96ZIYAS9riLo8XQE5HFUAXBpXpxbbCxVag3HhRfsu7Hpkngg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2020-7-1
  tags:
    - tumor immunology
    - transplant immunology
    - systems biology
