# Aleksandar Obradovic
- id: doi:10.1016/j.ccell.2023.04.003
  image: https://www.cell.com/cms/attachment/7114db8b-9334-44f7-9bc1-2e60885fba76/fx1.jpg
  date: 2023-4-27
  tags:
    - tumor immunology
    
- id: doi:10.1126/science.adg5585
  image: https://www.science.org/cms/10.1126/science.adg5585/asset/99b9ccec-6750-4ded-aa1a-852395094276/assets/images/large/science.adg5585-f1.jpg
  date: 2023-2-16
  tags:
    - tumor immunology
    
- id: doi:10.1101/2023.01.01.522340
  image: https://www.frontiersin.org/files/Articles/894508/fimmu-13-894508-HTML/image_m/fimmu-13-894508-g001.jpg
  date: 2023-1-2
  tags:
    - tumor immunology    

- id: doi:10.1016/j.eururo.2022.09.004
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0302283822026331-gr4.jpg
  date: 2022-9-13
  tags:
    - tumor immunology

- id: doi:10.1158/1078-0432.CCR-21-3570
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/28/10/1/m_clincanres_28_10_cover.png?Expires=1670637786&Signature=jSMXWL0ltcrOtSRQQAGCRH-htWusGEmusO9J58m3BPV24G3gIwSprQyEwn6HQGwYikYFLIWmSuYWKe17oFkbGNgJxoEPmcH0Fxv0nes5mSGeJVnJBXy8nj5wDug4urIglbhX9dkP5cgLgDJXCz9ZaoC8iaeg8NNcT0QQvYo0mT7udcAY8F5dODrZSVE1UA5QU8u01P2hHdqKj46yjAYdrs8W3QSCfH15ecjTaFmAsCGIzXP~nW8l2Lxi9sYzZ1wqtWZPnZOczrcSSX4WAz9UBjOSaWgYR2pkyW8l7EdaHwjEl3lHas-noLD6t0Hyww7ezb-2aMsHb9n7izJ6kiHqng__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2022-5-15
  tags:
    - tumor immunology
    - systems biology

- id: doi:10.1002/path.5830
  image: https://onlinelibrary.wiley.com/cms/asset/35734156-4f8a-43f6-8224-38e1ca03aa77/path5830-fig-0001-m.jpg
  date: 2021-11-3
  tags:
    - tumor immunology
   
#2016-10-21
- id: doi:10.1126/sciimmunol.aah3732
  image: https://www.science.org/cdn-cgi/image/width=400/cms/asset/8086faf2-5472-4b1b-b40f-6fc96af7afba/sciimmunol.2022.7.issue-77.largecover.jpg
  date: 2016-10-1
  tags:
    - transplant immunology

- id: doi:10.1111/ajt.14251
  image: https://onlinelibrary.wiley.com/cms/asset/5f154fda-7bbc-4df0-8935-adf27c5f2f9a/ajt.2017.17.issue-8.cover.jpg
  date: 2017-3-1
  tags:
    - transplant immunology
    
- id: doi:10.1172/jci.insight.121256
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6129121/bin/jciinsight-3-121256-g161.jpg
  date: 2018-8-9
  tags:
    - transplant immunology
    - systems biology

#2018-11-15
- id: doi:10.1172/jci.insight.124086
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6302945/bin/jciinsight-3-124086-g085.jpg
  date: 2018-11-1
  tags:
    - transplant immunology

- id: doi:10.1016/j.stem.2018.11.007
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1934590918305435-fx1.jpg
  date: 2019-2-7
  tags:
    - transplant immunology

- id: doi:10.1172/JCI124358
  image: https://dm5migu4zj3pb.cloudfront.net/manuscripts/124000/124358/medium/JCI124358.f1.jpg
  date: 2019-3-28
  tags:
    - transplant immunology
    - systems biology

#2019-10-25
- id: doi:10.1186/s40425-019-0758-y
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs40425-019-0758-y/MediaObjects/40425_2019_758_Fig1_HTML.png?as=webp
  date: 2019-10-1
  tags:
    - tumor immunology

- id: doi:10.1111/ajt.15533
  image: https://onlinelibrary.wiley.com/cms/asset/bcf8def5-571f-4bb6-8500-a48289dac414/ajt.v20.1.cover.jpg
  date: 2019-7-18
  tags:
    - transplant immunology

- id: doi:10.1158/1078-0432.CCR-19-3372
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/26/13/5/m_clincanres_26_13_cover.png?Expires=1670672831&Signature=oA7~tg4Mu8yG87gonUWuDY7O8O6w-vpd-ZD3zfandGMPzJ2oLPQaThtcfa32BwoWT0eJ-QUiA0mrWAnW6dxpu3qBttoFCfrX-f8JKHnOMJHwe4UqbU2REtCWX7kqn3VEA86ci-R6Fxk2ZU6Mp3F6eej60daLnQ~7zKmlYCvNdavKDu6U~L0V236~XQA13LL6zasdQ~pi9GHqTpq3AIL4s8lrIZdhbocUXtupFW79IZ-p-4jd5SclOi4t-ffEa-IxvIy95~IPmqzn1OAPmQAgGZaN0-BlQHcSuAZGNT96ZIYAS9riLo8XQE5HFUAXBpXpxbbCxVag3HhRfsu7Hpkngg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2020-7-1
  tags:
    - tumor immunology

- id: doi:10.1158/1078-0432.CCR-20-1610
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/clincancerres/issue/27/2/2/m_clincanres_27_2_cover.png?Expires=1670672959&Signature=xrs81QSBdXrBYoKEHnt0w0RAthzh00ZFLKXGy8hr~G9tM1LFHT1kkS-WX0riCHBDRgiDyzq2YMrRq~FbM8WtN-SQ~92K0Jntkc2yGYInj0mc~Pbe6mvsRyN~-3YPRpgNxP5GiR8CcZJRffwz29j~LK0Ta3lyJFRWlMXNNkBG~H8s94LQkvcpTd~KdfmHtfUvgyxBO0MpE0R~nNTmxDh4xiWxxF67IcWSJk~ZsatdEi1oDXuCgTRf-UT00~GqnUkJ9NjuajVNjcsbXPpIypi~omEQA1azc5klIF2AakFbMbTdhlnH65vmnZfC7d1NhCA7ZDUvgTZjhwD7rIHgH5noNg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2021-1-19
  tags:
    - tumor immunology

- id: doi:10.1101/2021.05.20.445002
  image: https://www.biorxiv.org/content/biorxiv/early/2022/01/25/2021.05.20.445002/F1.medium.gif
  date: 2022-1-25
  tags:
    - systems biology

- id: doi:10.1136/jitc-2020-001649
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8246381/bin/jitc-2020-001649f01.jpg
  date: 2021-6-30
  tags:
    - tumor immunology

- id: doi:10.1172/JCI141698
  image: https://dm5migu4zj3pb.cloudfront.net/manuscripts/141000/141698/medium/JCI141698.ga.jpg
  date: 2021-2-25
  tags:
    - transplant immunology

- id: doi:10.1111/ajt.16333
  image: https://onlinelibrary.wiley.com/cms/asset/3d54fafd-3b3d-493e-8657-9d9c8717fd81/ajt.v21.4.cover.jpg
  date: 2020-10-5
  tags:
    - transplant immunology

- id: doi:10.1158/2326-6066.CIR-20-0637
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerimmunolres/issue/9/5/3/m_canimm_9_5_cover.png?Expires=1670673789&Signature=I6p6qMTDvQAkxk5oNouyWpAs11nE4Tld9SJ5TQsi4qMnz999HsCXhrAZM97-kNHgR-sns8l4StKfUkdSYncposyUXXEQQzyV60HykeOyJGef4qr~0Y5iHmDVQ1StqryUp8-VI6DsAn1znGPB-90BHGtFp1yOkiuw11HI28Yj1pTG-TSwcNZcf~8oqUbN1UW4zZrKaPiCbkiIEfSAyzK9eOITUb5D7uTMH5i4eHlAOgLfI1PKydn-efO0T6LG1V8gBqLtZWTSJij1Ob6ugcHcAnebMTsBlOXEHxjnu~TOVLl4LrFUw~fyfP-DlEK4U6uj5N13CpqOviq8dZRUKKZLXw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  date: 2021-5-1
  tags:
    - tumor immunology

- id: doi:10.1016/j.cell.2021.04.038
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867421005730-fx1.jpg
  date: 2021-5-27
  tags:
    - tumor immunology
    - systems biology

- id: doi:10.1038/s43018-021-00227-3
  image: https://media.springernature.com/lw685/springer-static/esm/art%3A10.1038%2Fs43018-021-00227-3/MediaObjects/43018_2021_227_Fig11_ESM.jpg?as=webp
  date: 2021-7-19
  tags:
    - tumor immunology

- id: doi:10.1016/j.simpa.2021.100142
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2665963821X00048-cov150h.gif
  date: 2021-10-2
  tags:
    - transplant immunology
    - systems biology

- id: doi:10.1101/2022.02.22.481404
  image: https://www.biorxiv.org/content/biorxiv/early/2022/02/23/2022.02.22.481404/F1.large.jpg?width=800&height=600&carousel=1
  date: 2022-2-23
  tags:
    - tumor immunology
    - systems biology

- id: doi:10.1101/2022.02.28.482410
  image: https://www.biorxiv.org/content/biorxiv/early/2022/03/02/2022.02.28.482410/F1.large.jpg?width=800&height=600&carousel=1
  date: 2022-3-2
  tags:
    - systems biology

- id: doi:10.1101/2022.05.06.490968
  image: https://www.biorxiv.org/content/biorxiv/early/2022/05/09/2022.05.06.490968/F1.large.jpg?width=800&height=600&carousel=1
  date: 2022-5-9
  tags:
    - tumor immunology
    - systems biology
